### ISSUE TITLE
Design Overhaul

### ISSUE THREAD

**Issue by crr** [crrio/maple.fm#1]
### Description
The current design of the Maple.fm frontend presents many problems regarding accessibility and functionality across all devices, as well as other poor UX when directly interacting with the search and database areas.

### Roadmap
- [ ]  Complete overhaul of web appearance with a responsive design.
- [ ] Implement responsive ads to replace block ads.
- [ ] More added shortly.
